
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
*/

// Code generated by code-generation. DO NOT EDIT.

#include <unity.h>

#include "plc4c/spi/read_buffer.h"
#include "plc4c/spi/write_buffer.h"

#include "modbus_tcp_adu.h"


void internal_assert_arrays_equal(uint8_t* expected_array, uint8_t* actual_array, uint8_t num_bytes);

        
void parser_serializer_test_modbus_read_write_read_input_registers_request() {
            
    uint8_t payload[] = {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0xff, 0x04, 0x08, 0xd2, 0x00, 0x02
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, false, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        
void parser_serializer_test_modbus_read_write_read_input_registers_response() {
            
    uint8_t payload[] = {
        0x7c, 0xfe, 0x00, 0x00, 0x00, 0xc9, 0xff, 0x04, 0xc6, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xdb, 0x00, 0x00, 0x01, 0xd6, 0x00, 0x00, 0x4a, 0x38, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x64, 0x61, 0x69, 0x6d, 0x00, 0x6e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x31, 0x00, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, true, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        
void parser_serializer_test_modbus_read_write_read_extended_registers_request_split_file_record() {
            
    uint8_t payload[] = {
        0x00, 0x0a, 0x00, 0x00, 0x00, 0x11, 0x01, 0x14, 0x0e, 0x06, 0x00, 0x03, 0x27, 0x0e, 0x00, 0x02, 0x06, 0x00, 0x04, 0x00, 0x00, 0x00, 0x08
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, false, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        
void parser_serializer_test_modbus_read_write_read_extended_registers_response_split_file_record() {
            
    uint8_t payload[] = {
        0x00, 0x0a, 0x00, 0x00, 0x00, 0x1b, 0x01, 0x14, 0x18, 0x05, 0x06, 0x00, 0x00, 0x00, 0x00, 0x11, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, true, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        
void parser_serializer_test_modbus_read_write_write_extended_registers_request_file_record() {
            
    uint8_t payload[] = {
        0x00, 0x0a, 0x00, 0x00, 0x00, 0x0c, 0x01, 0x15, 0x09, 0x06, 0x00, 0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x08
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, false, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        
void parser_serializer_test_modbus_read_write_write_extended_registers_request_split_file_record() {
            
    uint8_t payload[] = {
        0x00, 0x0a, 0x00, 0x00, 0x00, 0x15, 0x01, 0x15, 0x12, 0x06, 0x00, 0x01, 0x27, 0x0F, 0x00, 0x01, 0x00, 0x00, 0x06, 0x00, 0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00
    };
    uint16_t payload_size = sizeof(payload);

    // Create a new read_buffer instance
    plc4c_spi_read_buffer* read_buffer;
    plc4c_return_code return_code =
    plc4c_spi_read_buffer_create(payload, payload_size, &read_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error creating read buffer");
    }

    plc4c_modbus_read_write_modbus_tcp_adu* message = NULL;
    return_code = plc4c_modbus_read_write_modbus_tcp_adu_parse(read_buffer, false, &message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error error parsing tpkt packet");
    }

    plc4c_spi_write_buffer* write_buffer;
    return_code = plc4c_spi_write_buffer_create(payload_size, &write_buffer);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error writing to buffer");
    }

    return_code = plc4c_modbus_read_write_modbus_tcp_adu_serialize(write_buffer, message);
    if (return_code != OK) {
        TEST_FAIL_MESSAGE("Error serializing");
    }

    internal_assert_arrays_equal(payload, write_buffer->data, payload_size);

    printf("Success");
}
        


void parser_serializer_test_modbus_read_write(void) {
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_read_input_registers_request);
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_read_input_registers_response);
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_read_extended_registers_request_split_file_record);
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_read_extended_registers_response_split_file_record);
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_write_extended_registers_request_file_record);
        
    RUN_TEST(
        parser_serializer_test_modbus_read_write_write_extended_registers_request_split_file_record);
        
}
    